const categoryTypes = {
    ALL_CATEGORIES_START : 'ALL_CATEGORIES_START',
    ALL_CATEGORIES_SUCCESS : 'ALL_CATEGORIES_SUCCESS',
    ALL_CATEGORIES_ERROR : 'ALL_CATEGORIES_ERROR',

    SELECT_CATEGORY : 'SELECT_CATEGORY',
}


export default categoryTypes;