# Generated by Django 2.2.4 on 2019-08-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('foundation_date', models.DateField()),
                ('tag_line', models.CharField(blank=True, max_length=150)),
                ('logo_url', models.URLField(max_length=300)),
                ('address', models.TextField()),
                ('contact_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gmap_src', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=300)),
                ('caption', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Brand')),
            ],
        ),
    ]
