# Generated by Django 2.2.4 on 2019-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=554, null=True),
        ),
    ]
