# Generated by Django 2.2.4 on 2019-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20191028_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
