# Generated by Django 2.2.4 on 2019-11-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_privacypolicy_returnpolicy_termcondition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.AlterModelOptions(
            name='returnpolicy',
            options={'verbose_name_plural': 'Return Policies'},
        ),
    ]
