const departmentTypes = {
    GET_DEPARTMENTS_START : 'GET_DEPARTMENTS_START',
    GET_DEPARTMENTS_SUCCESS : 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_ERROR : 'GET_DEPARTMENTS_ERROR',
}

export default departmentTypes;