const userTypes = {

    SET_LOGIN_EXPANDED : 'SET_LOGIN_EXPANDED',

    GET_AUTHTOKEN_START : 'GET_AUTHTOKEN_START',
    GET_AUTHTOKEN_SUCCESS : 'GET_AUTHTOKEN_SUCCESS',
    GET_AUTHTOKEN_ERROR : 'GET_AUTHTOKEN_ERROR',

    GET_CUSTOMER_START : 'GET_CUSTOMER_START',
    GET_CUSTOMER_SUCCESS : 'GET_CUSTOMER_SUCCESS',
    GET_CUSTOMER_ERROR : 'GET_CUSTOMER_ERROR',

    LOGOUT : 'LOGOUT',
}

export default userTypes;