const variantTypes = {
    CREATE_VARIANT_START : 'CREATE_VARIANT_START',
    CREATE_VARIANT_SUCCESS : 'CREATE_VARIANT_SUCCESS',
    CREATE_VARIANT_ERROR : 'CREATE_VARIANT_ERROR',
    
    SELECT_VARIANT : 'SELECT_VARIANT',
}

export default variantTypes;