# Generated by Django 2.2.4 on 2019-08-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='contact_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
