# Generated by Django 2.2.4 on 2019-12-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
