# Generated by Django 2.2.4 on 2020-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20200204_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
