# Generated by Django 2.2.4 on 2020-02-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20200216_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
