
const productVariantsTypes = {
    GET_PRODUCT_VARIANTS_START : 'GET_PRODUCT_VARIANTS_START',
    GET_PRODUCT_VARIANTS_SUCCESS : 'GET_PRODUCT_VARIANTS_SUCCESS',
    GET_PRODUCT_VARIANTS_ERROR : 'GET_PRODUCT_VARIANTS_ERROR',

}

export default productVariantsTypes;