# Generated by Django 2.2.4 on 2019-08-06 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_productimage_sublet_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
