# Generated by Django 2.2.4 on 2019-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_sublet_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
