# Generated by Django 2.2.4 on 2019-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20190821_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='color_hex',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
