# Generated by Django 2.2.4 on 2019-11-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_order_singleorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover_image', models.URLField(max_length=400)),
                ('desc', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ending_date', models.DateField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='Shop.Product')),
            ],
        ),
    ]
