# Generated by Django 2.2.4 on 2020-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
