# Generated by Django 2.2.4 on 2020-01-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_auto_20200118_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublet',
            name='stock',
        ),
    ]
