# Generated by Django 3.0.4 on 2020-03-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_canclledorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanclledOrder',
            new_name='CanceledOrder',
        ),
    ]
