# Generated by Django 3.0.4 on 2020-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20200314_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledorder',
            name='reason_for_cancel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
