# Generated by Django 3.0.4 on 2020-03-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
