# Generated by Django 3.0.4 on 2020-03-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_confirmed', models.BooleanField(default=False)),
                ('return_completed', models.BooleanField(default=False)),
                ('single_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Shop.SingleOrder')),
            ],
        ),
    ]
