# Generated by Django 2.2.4 on 2020-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_auto_20200315_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
