const productsTypes = {
    ALL_PRODUCTS_START : 'ALL_PRODUCTS_START',
    ALL_PRODUCTS_SUCCESS : 'ALL_PRODUCTS_SUCCESS',
    ALL_PRODUCTS_ERROR : 'ALL_PRODUCTS_ERROR',

    PRODUCT_CREATE_START : 'PRODUCT_CREATE_START',
    PRODUCT_CREATE_SUCCESS : 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_ERROR : 'PRODUCT_CREATE_ERROR',

    CLEAR_CREATED_PRODUCT : 'CLEAR_CREATED_PRODUCT',

}

export default productsTypes;