const userTypes = {
    SELLER_REGISTER_START : 'SELLER_REGISTER_START',
    SELLER_REGISTER_SUCCESS : 'SELLER_REGISTER_SUCCESS',
    SELLER_REGISTER_ERROR : 'SELLER_REGISTER_ERROR',

    SELLER_LOGIN_START : 'SELLER_LOGIN_START',
    SELLER_LOGIN_SUCCESS : 'SELLER_LOGIN_SUCCESS',
    SELLER_LOGIN_ERROR : 'SELLER_LOGIN_ERROR',

    SELLER_TOKEN_START : 'SELLER_TOKEN_START',
    SELLER_TOKEN_SUCCESS : 'SELLER_TOKEN_SUCCESS',
    SELLER_TOKEN_ERROR : 'SELLER_TOKEN_ERROR',

    SELLER_PROFILE_START : 'SELLER_PROFILE_START',
    SELLER_PROFILE_SUCCESS : 'SELLER_PROFILE_SUCCESS',
    SELLER_PROFILE_ERROR : 'SELLER_PROFILE_ERROR',

    SELLER_LOGOUT : 'SELLER_LOGOUT',

    UPDATE_PROFILE_START : 'UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS : 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR : 'UPDATE_PROFILE_ERROR',
}


export default userTypes;