const searchProductsTypes = {
    SEARCH_INPUT_CHANGE : 'SEARCH_INPUT_CHANGE',
    SEARCH_PRODUCTS_START : 'SEARCH_PRODUCTS_START',
    SEARCH_PRODUCTS_SUCCESS : 'SEARCH_PRODUCTS_SUCCESS',
    SEARCH_PRODUCTS_ERROR : 'SEARCH_PRODUCTS_ERROR',
}

export default searchProductsTypes;